### ISSUE TITLE
TypeError: amount.split is not a function

### ISSUE THREAD

**Issue by marcperrinp** [nash-io/api-client-typescript#10]
Trying to place a limit order, but I keep getting this error (`TypeError: amount.split is not a function`). But I [don't see any requirement](https://nash-io-public.gitlab.io/api-client-typescript/modules/_src_helpers_currency_.html#createcurrencyamount) on `amount`, except that it should be a string, which it is:

```
const order = await client.placeLimitOrder(
        true,
        createCurrencyAmount(amountString, CryptoCurrency.BTC),
        OrderBuyOrSell.SELL,
        OrderCancellationPolicy.GOOD_TIL_CANCELLED,
        createCurrencyPrice(price, CryptoCurrency.BTC, CryptoCurrency.USDC),
        'btc_usdc'
      )
```

Any clue what's going on?

**Comment by localhuman** [comment]
What are the values of `amountString` and `price` ?  Its possible it is expecting a decimal point?

**Comment by marcperrinp** [comment]
I use `.toFixed(6)` for the amount for the BTC/USDC pair, so `amountString` is worth '0.001056'.

Aah but `price` is `9378.250199999999`, so maybe that's the issue. Didn't think to check considering the error message. 

I'll check right now, thanks!

**Comment by marcperrinp** [comment]
Ok, that did the trick, thanks!
