### ISSUE TITLE
Nonce too large for uint32

### ISSUE THREAD

**Issue by marcperrinp** [nash-io/api-client-typescript#14]
On Nash Casino, players started getting the following error `Nonce too large for uint32` shortly after 10pm UTC. I confirmed this morning I'm getting the same error.

I understand what it must mean, but have no idea how to solve it.

Any help would be greatly appreciated! 😄

**Comment by marcperrinp** [comment]
I realize you may have just released a [fix for this](https://github.com/nash-io/api-client-typescript/commit/7b983977dfe31ee7ba8ef6786ce68e139d393569). I'll try and upgrade to 5.0.31 and see what happens.

**Comment by Marcpepe** [comment]
Ok it looks like it solved it 👍 

However I did run into something very worrying. Using the casino, I just made 2 limit orders:
- BUY $10 worth of BTC with USDC at $9,708
- SELL $10 worth of BTC for USDC at $9,558

![image](https://user-images.githubusercontent.com/4925054/85515078-0268d700-b5fd-11ea-996f-d1934f896267.png)

**Shouldn't the 2 orders have matched each other?** Or is this some kind of anti-wash-trading measure where one's orders cannot collide?

![image](https://user-images.githubusercontent.com/4925054/85515188-23312c80-b5fd-11ea-8b3c-2e4aec4e2e49.png)

**Comment by localhuman** [comment]
Yep! We don't allow wash trading for AML reasons.

**Comment by Marcpepe** [comment]
Alright, crystal clear! I was very funny to experience though, like walking through a wall 😄 

Closing issue but will create another quick one as I have another question.
