### ISSUE TITLE
Error: Could not place order: GraphQL error: Invalid timestamp using payload

### ISSUE THREAD

**Issue by DulajSP** [nash-io/api-client-typescript#20]
I'm getting following error when i try to place a limit order.
( Error: Could not place order: GraphQL error: Invalid timestamp using payload ) 

```
const order = await nash.placeLimitOrder(
            false,
            createCurrencyAmount("1", CryptoCurrency.GAS),
            OrderBuyOrSell.SELL,
            OrderCancellationPolicy.GOOD_TIL_CANCELLED,
            createCurrencyPrice("10", CryptoCurrency.USDC, CryptoCurrency.GAS),
            "gas_usdc"
          );
```

Any help would be appreciated.

**Comment by Marcpepe** [comment]
Hi @DulajSP, are you making that call from a server or a browser?

Anyway I think it might be the same error I'm getting: https://github.com/nash-io/api-client-typescript/issues/15#issuecomment-653743288

For me the timeout comes from a `dhFillRPool` request generated by the `placeLimitOrder` method.

**Comment by jankjr** [comment]
Hi @DulajSP 

I took some time to investigate the issue yesterday and found it was because the settings we are running the pool filling with are not suitable for the browser. I've exposed a method to reconfigure those settings here: https://github.com/nash-io/nash-protocol/pull/9

Once the MR has been merged and a new version of the protocol has been released you should be able to set it to a more appropriate level:
```
import {
  Client,
  EnvironmentConfiguration
} from '@neon-exchange/api-client-typescript'
import {
  configurePoolSettings
} from '@neon-exchange/nash-protocol'

// This step is really important for browser usage
configurePoolSettings(10)
```

**Comment by DulajSP** [comment]
Thanks @Marcpepe  and @jankjr  
I'm making that calls from server and its looks like only initial order getting that error. As @Marcpepe said I think I have the same problem you had before.

**Comment by Marcpepe** [comment]
@DulajSP From the server, I do witness a lag (4-5s I'd say) when placing the very first order. But the order does go through and I don't get the "Invalid timestamp" error.

Maybe this has to do with your server location? But then the other calls would probably also fail..

**Comment by Marcpepe** [comment]
@DulajSP Do you have Telegram? If you do, ping me @marcpepe

**Comment by DulajSP** [comment]
Thanks @Marcpepe  
Yes, I'll text you.
