### ISSUE TITLE
Wrong amountExecuted returned

### ISSUE THREAD

**Issue by MehdiSangtarash** [nash-io/api-client-typescript#64]
I placed a limit order (placeLimitOrder), here is the params:

{
    "allowTaker": true,
    "amount": { "volume": "0.1", "currency": "btc"},
    "buyOrSell": "SELL",
    "cancellationPolicy": "GOOD_TIL_CANCELLED",
    "limitPrice": { "amount": "6499", "currencyA": "usdc", "currencyB": "btc" },
    "marketName": "btc_usdc"
}

the order was partially filled when I asked to getAccountOrder using orderId. amountExecuted.amount is equal to amount.amount when the order is not fully filled yet. the amountExecuted.amountRemaining is correct tho. here is the full response I get from the exchange:

{"amount":{"amount":"0.10000000","currency":"btc"},"amountExecuted":{"amount":"0.10000000","currency":"btc"},"amountRemaining":{"amount":"0.01777100","currency":"btc"},"avgExecutedPrice":{"amount":"6499.14480329","currencyA":"usdc","currencyB":"btc"},"buyOrSell":"SELL","cancelAt":null,"cancellationPolicy":"GOOD_TIL_CANCELLED","id":"1616487941280000000","limitPrice":
{"amount":"6499.00000000","currencyA":"usdc","currencyB":"btc"},"market":{"aUnit":"btc","aUnitPrecision":8,"bUnit":"usdc","bUnitPrecision":8,"minTickSize":"0.01","minTradeIncrement":"0.000001","minTradeIncrementB":"0.01","minTradeSize":"0.00010000","minTradeSizeB":"5.00000000","name":"btc_usdc","priceGranularity":12,"status":"RUNNING"},"oppositeAmountExecuted":{"amount":"534.41817803","currency":"usdc"},"placedAt":"2021-03-23T08:25:41.277981Z","status":"OPEN","stopPrice":null,"type":"LIMIT"}

there's probably a mistake here, right? or am I missing something?

**Comment by lucianoengel** [comment]
That is the correct response. Amount executed in most cases will be equal
to amount, unless in situations were the liquidity isn't enough to cover
the order amount.

 Like in a market order for 10 x in a market where there's only 5
available, it won't be possible to execute all the 10 x and in this case
amount = 10 and amount_executed = 5.
