### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by marcperrinp** [nash-io/api-client-typescript#7]
Small head's up on the documentation:

Searching for "placeLimit.." and clicking to on the `placeLimitOrder` method shows me [a 404](https://nash-io.github.io/api-client-typescript/docs/classes/_client_client_.client.html#placelimitorder) (whereas it is still available in [Gitlab pages](https://nash-io-public.gitlab.io/api-client-typescript/classes/_src_client_client_.client.html#placelimitorder))

**Comment by localhuman** [comment]
Yep, still working out the new docs here :)

**Comment by metachris** [comment]
The Github CDN is just updating the content of the docs. Should be all sorted out by itself in a few hours at latest. The content is in the [`gh-pages`](https://github.com/nash-io/api-client-typescript/tree/gh-pages) branch, but not yet deployed fully on their CDN.

In the meantime you could generate the docs locally with `yarn doc`

**Comment by marcperrinp** [comment]
Ah ok sure, my bad!

**Comment by metachris** [comment]
Seems to be a jekyll issue, that gh pages doesn't automatically work with underscores in filenames. 

Should be fixed with https://github.com/nash-io/api-client-typescript/pull/11

**Comment by metachris** [comment]
works now
